underwater_adversary_command_publisher:
  ros__parameters:
    current_magnitude: 1.5
pid_controllers:
  ros__parameters:
    pitch_gains: [0.01, 0.0, 0.25] #P,I,D
    depth_target: 11.0
    roll_gains: [2.75, 0.0, 3.75] #P,I,D
    roll_target: 0.0
    speed: 0.25


    