underwater_adversary_command_publisher:
  ros__parameters:
    current_magnitude: 0.5
pid_tuning:
  ros__parameters:
    pitch_gains: [0.5181, 0.0, 0.9] #P,I,D
    pitch_target: 40.0
    heave_gains: [0.25, 0.0, 0.5] #P,I,D
    depth_target: 8.0
    roll_gains: [2.75, 0.0, 3.75] #P,I,D
    roll_target: 0.0
    speed: 0.25



    