underwater_adversary_command_publisher:
  ros__parameters:
    current_magnitude: 1.5
pid_controllers:
  ros__parameters:
    pitch_gains: [0.2, 0.0, 0.125] #P,I,D
    pitch_target: 0.0
    roll_gains: [0.3, 0.0, 0.125] #P,I,D
    roll_target: 0.0
    depth_gains: [0.3, 0.0, 0.15] #P,I,D
    depth_target: -5.0
    